name: sabbar_task
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_local_notifications: ^9.7.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.1
  injectable: ^2.1.0
  intl: ^0.17.0
  material_color_utilities: ^0.1.5
  timelines: ^0.1.0

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
